#!/bin/sh
set -e
# Ensure convenient symlinks exist
ln -sf /usr/local/bin/python3.12 /usr/local/bin/python3 || true
ln -sf /usr/local/bin/python3.12 /usr/local/bin/python || true
ln -sf /usr/local/bin/pip3.12 /usr/local/bin/pip3 || true
ln -sf /usr/local/bin/pip3.12 /usr/local/bin/pip || true
exit 0

